version: '3'

services:
  app_vet:
    build: clinicaVet
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://veterinaria:3306/veterinaria?createDatabaseIfNotExist=true&serverTimeZone=UTC
      DB_USER_NAME: admin
      DB_PASSWORD: admin
    restart: always
    depends_on:
      veterinaria:
        condition: service_healthy

  veterinaria:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: veterinaria
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10